name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Julia environment
      # You may pin to the exact commit or the version.
      # uses: julia-actions/setup-julia@b315a4d9881690c63d53fc0175b150a3776140bd
      uses: julia-actions/setup-julia@v1.9.0
      with:
        # The Julia version to download (if necessary) and use. Example: 1.0.4
        version: 1.8.5 # optional, default is 1
        # Include prereleases when matching the Julia version to available versions.
        include-all-prereleases: false # optional, default is false
        # Architecture of the Julia binaries. Defaults to the architecture of the runner executing the job.
        arch: ${{ runner.arch }} # optional, default is ${{ runner.arch }}
        # Display InteractiveUtils.versioninfo() after installing
        show-versioninfo: true # optional, default is false
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build for Release
      run: cargo build --release
